name: disentanglement_challenge
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2019.5.15
  - cairo=1.14.12
  - certifi=2019.6.16
  - cffi=1.12.3
  - cudatoolkit=10.0.130
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - glib=2.56.2
  - graphite2=1.3.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - icu=58.2
  - intel-openmp=2019.4
  - jpeg=9b
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - mkl=2019.4
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - ncurses=6.1
  - ninja=1.9.0
  - olefile=0.46
  - openssl=1.1.1
  - pango=1.42.4
  - pcre=8.43
  - pillow=6.0.0
  - pip=19.1.1
  - pixman=0.38.0
  - pycparser=2.19
  - python=3.6.8
  - pytorch=1.1.0
  - readline=7.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - tk=8.6.8
  - torchvision=0.3.0
  - wheel=0.33.4
  - wxpython=4.0.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.7.1
    - astor==0.7.1
    - chardet==3.0.4
    - crowdai-api==0.1.21
    - cycler==0.10.0
    - dill==0.3.0
    - disentanglement-lib==1.0
    - enum34==1.1.6
    - future==0.17.1
    - gast==0.2.2
    - gin-config==0.1.4
    - grpcio==1.20.1
    - h5py==2.9.0
    - idna==2.8
    - imageio==2.5.0
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - kiwisolver==1.1.0
    - llvmlite==0.4.0
    - markdown==3.1
    - matplotlib==3.0.3
    - mock==3.0.4
    - numba==0.41.0
    - numpy==1.16.3
    - pandas==0.24.2
    - protobuf==3.7.1
    - pyparsing==2.4.0
    - python-dateutil==2.8.0
    - python-gitlab==1.9.0
    - pytz==2019.1
    - redis==3.2.1
    - requests==2.22.0
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - simplejson==3.16.0
    - tensorboard==1.13.1
    - tensorflow-estimator==1.13.0
    - tensorflow-gpu==1.13.1
    - tensorflow-hub==0.4.0
    - tensorflow-probability==0.6.0
    - termcolor==1.1.0
    - tqdm==4.32.2
    - urllib3==1.25.3
    - werkzeug==0.15.2
prefix: /home/amirabdi/miniconda3/envs/disentanglement_challenge

